// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACiDItQn2oj3-sAWOyjuIlkRo8zpN9RlA',
    appId: '1:299301176448:web:f24a581eca991be28fd265',
    messagingSenderId: '299301176448',
    projectId: 'healthyair-a4569',
    authDomain: 'healthyair-a4569.firebaseapp.com',
    storageBucket: 'healthyair-a4569.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHxwyFDD1yiwQFYqCWEcp8pUWGxGUVneA',
    appId: '1:299301176448:android:1c2d8e9eb82332208fd265',
    messagingSenderId: '299301176448',
    projectId: 'healthyair-a4569',
    storageBucket: 'healthyair-a4569.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjfOGW5ot9-K_1nPrb1xK-ToXw5eBG2GA',
    appId: '1:299301176448:ios:e7349f56fc2036fc8fd265',
    messagingSenderId: '299301176448',
    projectId: 'healthyair-a4569',
    storageBucket: 'healthyair-a4569.firebasestorage.app',
    iosBundleId: 'com.example.healthyair',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjfOGW5ot9-K_1nPrb1xK-ToXw5eBG2GA',
    appId: '1:299301176448:ios:e7349f56fc2036fc8fd265',
    messagingSenderId: '299301176448',
    projectId: 'healthyair-a4569',
    storageBucket: 'healthyair-a4569.firebasestorage.app',
    iosBundleId: 'com.example.healthyair',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACiDItQn2oj3-sAWOyjuIlkRo8zpN9RlA',
    appId: '1:299301176448:web:da2765f83deace6f8fd265',
    messagingSenderId: '299301176448',
    projectId: 'healthyair-a4569',
    authDomain: 'healthyair-a4569.firebaseapp.com',
    storageBucket: 'healthyair-a4569.firebasestorage.app',
  );
}
